# QUESTION 1

In [2]:
import numpy as np
array = np.arange(2,51,3)
array

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

# QUESTION 2 

In [4]:
import numpy as np 
l1 = []
l2 = []
for i in range(5):
    x=int(input("enter number for list1 :"))
    l1.append(x)
for i in range(5):
    x=int(input("enter number for list2 :"))
    l2.append(x)
a1=np.array(l1)
a2=np.array(l2) 
arr = np.concatenate((a1, a2))
print("\nArray value for concatenated arr :",arr) 
sortArr = np.sort(arr)
print("\nSorted Array for concatenated arr :",sortArr)


enter number for list1 :56
enter number for list1 :78
enter number for list1 :49
enter number for list1 :50
enter number for list1 :30
enter number for list2 :21
enter number for list2 :5
enter number for list2 :61
enter number for list2 :39
enter number for list2 :40

Array value for concatenated arr : [56 78 49 50 30 21  5 61 39 40]

Sorted Array for concatenated arr : [ 5 21 30 39 40 49 50 56 61 78]


# QUESTION 3

In [6]:
arr = np.array([ [1,2,3] , [4,5,6] , [7,8,9] ])

print("shape",arr.shape,"size",arr.size)

shape (3, 3) size 9


# QUESTION 4

In [12]:
arr = np.array([[1,2,3,4,5,6,7,8,9]])

print(arr,arr.shape) 

print()

arr = arr.reshape(3,3) 

print(arr,arr.shape)


[[1 2 3 4 5 6 7 8 9]] (1, 9)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


# QUESTION 5

In [13]:
arr1=np.random.rand(3,3)
arr2=np.random.rand(3,3)
print(np.vstack((arr1,arr2)))
print() 
print(np.hstack((arr1,arr2))) 

[[0.71339754 0.99845188 0.59958055]
 [0.62703907 0.59097101 0.21300945]
 [0.94377728 0.55782607 0.26859856]
 [0.4236063  0.16370416 0.47947741]
 [0.33723318 0.96658236 0.89241145]
 [0.54444851 0.72961526 0.0755142 ]]

[[0.71339754 0.99845188 0.59958055 0.4236063  0.16370416 0.47947741]
 [0.62703907 0.59097101 0.21300945 0.33723318 0.96658236 0.89241145]
 [0.94377728 0.55782607 0.26859856 0.54444851 0.72961526 0.0755142 ]]


# QUESTION 6

In [16]:
arr_1 = np.array([5,6,5, 1, 2, 11,8, 25, 3, 2, 7, 6, 5, 7, 8, 11])
print(np.unique(arr_1,return_counts=True))

(array([ 1,  2,  3,  5,  6,  7,  8, 11, 25]), array([1, 2, 1, 3, 2, 2, 2, 2, 1], dtype=int64))
